MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data/ship/chi_vit/checkpoint.pth'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'chivit_base_ibot'
  STRIDE_SIZE: [16, 16]
  MIE: True
  MIE_COE: 3.0
  SSE: False
  PAIR: True
  USE_AMP: True
  DIST_TRAIN: True
  METRIC_LOSS_TYPE: 'ibot'
  RGB_CHANNELS: [0, 1, 2]
  SAR_CHANNELS: [10, 11]

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN_RGB: [0.485, 0.456, 0.406]
  PIXEL_STD_RGB: [0.229, 0.224, 0.225]
  PIXEL_MEAN_SAR: [0.340619, 0.340619, 0.340619]
  PIXEL_STD_SAR: [0.276758, 0.276758, 0.276758]

IBOT:
  OUT_DIM: 8192
  PATCH_OUT_DIM: 8192
  SHARED_HEAD: False
  SHARED_HEAD_TEACHER: True
  NORM_LAST_LAYER: True
  NORM_IN_HEAD: ''
  ACT_IN_HEAD: 'gelu'
  HEAD_NLAYERS: 3
  HEAD_HIDDEN_DIM: 2048
  HEAD_BOTTLENECK_DIM: 256
  GLOBAL_CROPS_NUMBER: 2
  LOCAL_CROPS_NUMBER: 10
  GLOBAL_CROPS_SCALE: [0.32, 1.0]
  LOCAL_CROPS_SCALE: [0.05, 0.32]
  GLOBAL_SIZE: 224
  LOCAL_SIZE: 96
  PRED_RATIO: [0.0, 0.7]
  PRED_RATIO_VAR: [0.0, 0.05]
  PRED_SHAPE: 'rand'
  PRED_START_EPOCH: 0
  WARMUP_TEACHER_TEMP: 0.04
  TEACHER_TEMP: 0.06
  WARMUP_TEACHER_PATCH_TEMP: 0.04
  TEACHER_PATCH_TEMP: 0.06
  WARMUP_TEACHER_TEMP_EPOCHS: 30
  MOMENTUM_TEACHER: 0.996
  LAMBDA1: 1.0
  LAMBDA2: 1.0
  CLIP_GRAD: 0.5
  FREEZE_LAST_LAYER_EPOCHS: 1
  SAMPLING_SUBSET: True
  SYNC_CHANNEL_COUNT: True
  MODALITY_PURE_SAMPLING: False

DATASETS:
  NAMES: ('HOSS')
  ROOT_DIR: ('/data/ship')
  EVAL_MODE: 'all'

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 200
  BASE_LR: 3e-3
  IMS_PER_BATCH: 1024
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 5
  SCHEDULER_TYPE: 'wsd'
  WSD_DECAY_PCT: 0.1
  WSD_DECAY_TARGETS: (20, 40, 80, 100, 120, 160)
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 100
  EVAL_PERIOD: 1
  LOG_PERIOD: 10
  TRACK_VALIDATION_METRICS: True
  TRACK_VALIDATION_METRICS_OPTISAR: False
  PRETRAIN_TRACK_VALIDATION_DIR: '/data/ship/vessel_re_id/'
  SEED: 42
  WEIGHT_DECAY: 1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  USE_MULTI_PRETRAIN: True
  DETERMINISTIC: False

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '/data/ship/vessel_re_id/checkpoints/pretrain_chi_vit_ibot'

WANDB:
  PROJECT: 'vessel-reid-pretraining'
  NAME: 'pretrain-chi-vit-ibot'
